apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: {{ .Chart.Name }}
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: shell
          configMap:
            name: {{ .Chart.Name }}-config
            defaultMode: 0777
      containers:
        - image: alpine:3.12.0
          name: {{ .Chart.Name }}
          volumeMounts:
            - name: shell
              mountPath: /shell
          command:
            - sh
            - -c
            - /shell/exec_shell.sh
          env:
            - name: init_sink_name
              value: {{ .Values.global.init_sink_name }}
            - name: tasks_max
              value: {{ .Values.global.tasks_max |quote }}
            - name: topics
              value: {{ .Values.global.topics }}
            - name: flush_size
              value: {{ .Values.global.flush_size |quote }}
            - name: store_url
              value: {{ .Values.global.store_url }}
            - name: s3_bucket_name
              value: {{ .Values.global.s3_bucket_name }}
            - name: aws_access_key_id
              valueFrom:
                secretKeyRef:
                  name: mdsp-secret-infra-credentials
                  key: ceph_access_key_id
            - name: aws_secret_access_key
              valueFrom:
                secretKeyRef:
                  name: mdsp-secret-infra-credentials
                  key: ceph_access_key_secret
            - name: action
              value: {{.Values.global.action}}
            - name: num_partitions
              value: {{.Values.global.num_partitions |quote}}
            - name: replication_factor
              value: {{.Values.global.replication_factor |quote}}
            - name: brokers
              value: {{.Values.global.brokers}}