apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
    aws_access_key_id: {{ .Values.global.aws_access_key_id | b64enc | quote }}
    aws_secret_access_key: {{ .Values.global.aws_secret_access_key | b64enc | quote }}
