apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: {{ .Chart.Name }}
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: config
          configMap:
            name: {{ .Chart.Name }}-info
        - name: shell
          configMap:
            name: {{ .Chart.Name }}-shell
            defaultMode: 0777
      containers:
        - image: alpine:3.12.0
          name: {{ .Chart.Name }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: shell
              mountPath: /shell
          command:
            - sh
            - -c
            - /shell/exec_shell.sh
          env:
            - name: rabbitmqapiurl
              value: {{ .Values.global.rabbitmqapiurl }}
            - name: rabbitmquser
              value: {{ .Values.global.rabbitmquser }}
            - name: rabbitmqpassword
              value: {{ .Values.global.rabbitmqpassword }}
