- name: Create zk Directory
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  changed_when: false
  with_items:
    - '{{ data_dir }}/zookeeper'

- name: get zk from official website
  get_url:
    dest: /tmp/
    url: https://archive.apache.org/dist/zookeeper/zookeeper-3.6.1/apache-zookeeper-3.6.1-bin.tar.gz
    validate_certs: no
    force: no
- name: unarchive remote file to remote dir
  unarchive:
    src: /tmp/apache-zookeeper-3.6.1-bin.tar.gz
    dest: /usr/local/
    mode: 0755
    copy: no # whether to copy local ansible service's file to remote or just use remote file
- name: iink zk file
  file:
    src: /usr/local/apache-zookeeper-3.6.1-bin
    dest: /usr/local/zookeeper
    state: link

- name: render templates config to zk conf
  template:
    src: zoo.cfg.j2
    dest: /usr/local/zookeeper/conf/zoo.cfg
    owner: root
    group: root
# can replaced by template
- name: config myid
  shell: echo "{{myid}}" > /data/zookeeper/myid

- name: copy zookeeper service
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service

- name: start zookeeper
  systemd:
    name: zookeeper
    state: started
    enabled: yes
    daemon_reload: yes

