apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-ceph-sink.fullname" . }}
  labels:
    {{- include "kafka-ceph-sink.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kafka-ceph-sink.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kafka-ceph-sink.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kafka-ceph-sink.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.customEnv.CUSTOM_SCRIPT_PATH }}
          command: 
          - /bin/bash
          - -c
          - $CUSTOM_SCRIPT_PATH
          {{- end }}
          env:
          - name: CUSTOM_SCRIPT_PATH
            value: "{{ .Values.customEnv.CUSTOM_SCRIPT_PATH }}"
          - name: KAFKA_DIR
            value: "{{.Values.customEnv.KAFKA_DIR}}"
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "{{.Values.customEnv.KAFKA_DIR}}/config/connect-distributed.properties"
              name: worker-config
              subPath: connect-distributed.properties
      volumes:
      - name: worker-config
        configMap:
          name: {{ template "kafka-ceph-sink.fullname" . }}-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
