- name:  config epel repo
  yum_repository:
    name: epel
    baseurl: http://mirrors.aliyun.com/epel/7/$basearch
    state: present
    gpgcheck: no
    repo_gpgcheck: no
    file: epel
    enabled: yes
    skip_if_unavailable: yes
    description: epel repo
- name: Change policy and state of SELinux
  selinux:
    configfile: /etc/selinux/config
    state: disabled
- name: Manage firewalld service
  systemd:
    daemon_reload: yes
    name: firewalld.service
    state: stopped
    enabled: no



