- name:  config epel repo
  yum_repository:
    name: epel
    baseurl: http://mirrors.aliyun.com/epel/7/$basearch
    state: present
    gpgcheck: no
    repo_gpgcheck: no
    file: epel
    enabled: yes
    skip_if_unavailable: yes
    description: epel repo
- name: Change policy and state of SELinux
  selinux:
    configfile: /etc/selinux/config
    state: disabled
- name: Manage firewalld service
  systemd:
    daemon_reload: yes
    name: firewalld.service
    state: stopped
    enabled: no
- name: Change NoFiles Limit Edited security/limits.conf
  pam_limits:
    domain: '*'
    limit_type: '-'
    limit_item: nofile
    value: 500000
    comment: increased file creation limit
- name: add hostname and ip bindings
  lineinfile:
    dest: /etc/hosts
    line: "{{ansible_eth0.ipv4.address}}  {{ansible_hostname|lower}}"
    state: present
    insertafter: "127.0.0.1"
- name: Increase File Handler Size change on sysctl.conf
  sysctl:
    sysctl_file: /etc/sysctl.d/fsfilemax.conf
    reload: yes
    state: present
    name: fs.file-max
    value: 500000
- name: install based tools
  yum: name='{{ item }}' state=present
  with_items:
    - yum-versionlock
    - bind-utils
    - python-pip
