---
# handlers file for rabbitmq
- name: reload-rabbitmq-server
  systemd:
    name: rabbitmq-server
    daemon_reload: yes

- name: start-rabbitmq-server
  systemd:
    name: rabbitmq-server
    state: started

- name: stop-rabbitmq-server
  systemd:
    name: rabbitmq-server
    state: stopped

- name: restart-rabbitmq-server
  systemd:
    name: rabbitmq-server
    state: restarted
